security:
  basic:
    enabled: false #turn off security on application endpoints

management:
  security:
    enabled: false #turn off secure actuator endpoints

logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote

